[package]
name = "berry-timers"
version = "0.2.6"
description = "Berryworks — EverQuest Legends toolkit"
authors = ["you"]
edition = "2021"

[lib]
name = "berry_timers_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
notify = "8"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
uuid = { version = "1", features = ["v4", "serde"] }
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
